# Generated by Django 5.1.1 on 2024-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temple',
            old_name='ชื่อ',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='temple',
            name='พระเกจิ',
        ),
        migrations.AddField(
            model_name='temple',
            name='geji',
            field=models.CharField(default=1, max_length=255, verbose_name='geji'),
            preserve_default=False,
        ),
    ]
