# Generated by Django 5.1.1 on 2024-09-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0002_rename_ช_อ_temple_name_remove_temple_พระเกจ__and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temple',
            name='geji',
        ),
        migrations.RemoveField(
            model_name='temple',
            name='name',
        ),
        migrations.AddField(
            model_name='temple',
            name='ชื่อ',
            field=models.CharField(default=1, max_length=255, verbose_name='ชื่อ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temple',
            name='พระเกจิ',
            field=models.CharField(default=1, max_length=255, verbose_name='พระเกจิ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temple',
            name='รายละเอียด',
            field=models.CharField(default=1, max_length=255, verbose_name='รายละเอียด'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temple',
            name='ลองติจูด',
            field=models.CharField(default=1, max_length=255, verbose_name='longtijud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temple',
            name='ละติจูด',
            field=models.CharField(default=1, max_length=255, verbose_name='ละติจูด'),
            preserve_default=False,
        ),
    ]
