# Generated by Django 5.1.1 on 2024-09-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0003_remove_temple_geji_remove_temple_name_temple_ช_อ_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temple',
            old_name='รายละเอียด',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='temple',
            old_name='ละติจูด',
            new_name='latijud',
        ),
        migrations.RenameField(
            model_name='temple',
            old_name='ลองติจูด',
            new_name='longtijud',
        ),
        migrations.RenameField(
            model_name='temple',
            old_name='พระเกจิ',
            new_name='namemunk',
        ),
        migrations.RenameField(
            model_name='temple',
            old_name='ชื่อ',
            new_name='nametemple',
        ),
    ]
