# Generated by Django 5.1.1 on 2024-09-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temple', '0004_rename_รายละเอ_ยด_temple_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='longtijud',
            field=models.CharField(max_length=255, verbose_name='ลองติจูด'),
        ),
    ]
